version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://kapelczak_user:your_secure_password@postgres:5432/kapelczak_notes
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=kapelczak_user
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=kapelczak_notes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: