version: "3.8"

services:
  app:
    container_name: kapelczak-notes-app
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://kapelczak_user:your_secure_password@db:5432/kapelczak_notes
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - db
    restart: always

  db:
    container_name: kapelczak-notes-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: kapelczak_notes
      POSTGRES_USER: kapelczak_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  pgdata:
